FROM node:15.4.0

COPY . /app
WORKDIR /app

EXPOSE 3000
ENV PORT=3000
ENV NODE_ENV=development
ENV MONGO_DB_CONNECTION_STRING=mongodb+srv://gcp-Frost:egj93kcp@cluster0.yn7cyou.mongodb.net/?retryWrites=true&w=majority
ENV MONGO_DB_NAME=Cluster0
ENV REDIS_URI=rediss://default:AVNS_B3kd3v6p5lv10cjGDwO@redis-7b8d793-andersenlukas-103c.aivencloud.com:15883

RUN npm install

CMD ["npm", "start"]
